version: "3.9"

services:
  de-eventbooking:
    image: php:8-apache
    container_name: de-eventbooking
    restart: unless-stopped

    working_dir: /var/www/html

    volumes:
      - /opt/containers/websites/de-eventbooking:/var/www/html
      - /opt/containers/websites/apache/servername.conf:/etc/apache2/conf-available/servername.conf
    
    networks:
      - traefik-proxy

    labels:
      - traefik.enable=true
      - traefik.http.routers.de-eventbooking.entrypoints=https
      - traefik.http.routers.de-eventbooking.tls=true
      - traefik.http.routers.de-eventbooking.tls.certresolver=http
      - traefik.http.routers.de-eventbooking.rule=Host(`tickets.ob5.de`)
      - traefik.http.services.de-eventbooking.loadbalancer.server.port=80

networks:
  traefik-proxy:
    external: true
